---
title: "Yelp- help us find our next favorite restaurant!"
author: "Stephanie Izard (smi2112), Anu Kafi (ak4123), Sarah Vititoe (sev2125)"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Team registration and proposal 
####First, you will define your teams and propose a project. This proposal should be a half-page to a page in length and include:

####Motivation

####Data Source

####Intended final produces


####The planned analyses, visualizations, and coding challenges

We plan to 

We plan to use ggplot and plotly to create visualizations that consider geographical location, rating, and price of the restaurant in 2018 as well as longitudinally. We will also create visualizations that consider reviewer information, such as number of reviews and average rating. The primary coding challenge that we anticipate is uploading the Yelp data into R, as it is currently a JSON file and none of us are familiar with the jsonlite package yet.

####Proposed timeline

